name: deployToAzure
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      packageName:
        required: true
        type: string
    secrets:
      azureWebAppName:
        required: true
      azurePublishProfile:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - name: Download All artifacts
      uses: actions/download-artifact@v2

    #- name: Run Azure webapp deploy to ${{ inputs.environmentName }} using publish profile credentials
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ inputs.AZURE_WEBAPP_NAME }} # Replace with your app name
    #    publish-profile: ${{ secrets.azurePublishProfile }} # Define secret variable in repository settings as per action documentation
    #    package: ${{ inputs.packageName }}

    - name: print stuff
      run: |
        echo "packageName is  ${{ inputs.packageName }}"
        echo "azureWebAppName is ${{ secrets.azureWebAppName}}"
        echo "azurePublishProfile is ${{ secrets.azurePublishProfile}}"

    - name: print stuff2
      run : |
        echo 'printing envs'
        env